[package]
name = "vterm-sdl2-rs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
pkg-config = "0.3"

[dependencies]

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["ttf"]

